FROM eclipse-temurin:21
WORKDIR /workspace
COPY . /workspace
RUN apt-get update && apt-get install -y maven git
RUN mvn clean install
 # this is ignored when run using dev container
CMD ["mvn", "spring-boot:run"]