name: Print Code Change

on:
  push:
    branches:
      - main

jobs:
  print_code_change:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print message
        run: |
          echo "Code change:"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }}